version: '3.8'

services:
  ocr_service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka_network

networks:
  kafka_network:
    external: true
